"""
Confluence REST API client — creates KB article pages in the demo space.
"""
import base64
import os

import httpx

from src.extraction.models import KBArticle


def _auth_header() -> str:
    email = os.environ["CONFLUENCE_EMAIL"]
    token = os.environ["CONFLUENCE_API_TOKEN"]
    return "Basic " + base64.b64encode(f"{email}:{token}".encode()).decode()


def _base_url() -> str:
    return os.environ["CONFLUENCE_URL"].rstrip("/")


_SEVERITY_COLOURS = {"p1": "Red", "p2": "Yellow", "p3": "Blue", "p4": "Green", "unknown": "Grey"}


def _macro(name: str, body: str, params: dict[str, str] | None = None) -> str:
    param_xml = "".join(
        f'<ac:parameter ac:name="{k}">{v}</ac:parameter>' for k, v in (params or {}).items()
    )
    return (
        f'<ac:structured-macro ac:name="{name}" ac:schema-version="1">'
        f"{param_xml}"
        f"<ac:rich-text-body>{body}</ac:rich-text-body>"
        f"</ac:structured-macro>"
    )


def _status_badge(severity: str) -> str:
    colour = _SEVERITY_COLOURS.get(severity, "Grey")
    return (
        f'<ac:structured-macro ac:name="status" ac:schema-version="1">'
        f'<ac:parameter ac:name="colour">{colour}</ac:parameter>'
        f'<ac:parameter ac:name="title">{severity.upper()}</ac:parameter>'
        f"</ac:structured-macro>"
    )


def _bullet_list(items: list[str]) -> str:
    if not items:
        return "<p><em>None</em></p>"
    lis = "".join(f"<li>{item}</li>" for item in items)
    return f"<ul>{lis}</ul>"


def _build_body(article: KBArticle) -> str:
    """Map KB article fields to Confluence storage format with native macros."""
    parts: list[str] = []

    # Summary — prominent lead paragraph
    parts.append(f"<p><strong>{article.summary}</strong></p>")

    # PII warning panel — shown early so reviewers see it immediately
    if article.pii_detected:
        fields_str = ", ".join(article.pii_fields)
        parts.append(
            _macro(
                "warning",
                f"<p><strong>PII detected</strong> in the following fields: {fields_str}. "
                "Review and redact before publishing or sharing this article.</p>",
            )
        )

    # Resolution first — what engineers scan for during an incident
    parts.append(f"<h2>Resolution</h2><p>{article.resolution}</p>")

    # Root cause — incidents only
    if article.root_cause:
        parts.append(f"<h2>Root Cause</h2><p>{article.root_cause}</p>")

    # Steps taken — collapse if verbose to keep the page scannable
    if article.steps_taken:
        steps_html = _bullet_list(article.steps_taken)
        if len(article.steps_taken) > 5:
            steps_content = _macro(
                "expand",
                steps_html,
                {"title": f"Steps Taken ({len(article.steps_taken)})"},
            )
        else:
            steps_content = steps_html
        parts.append(f"<h2>Steps Taken</h2>{steps_content}")

    # Prerequisites — howto / config only
    if article.prerequisites:
        parts.append(f"<h2>Prerequisites</h2>{_bullet_list(article.prerequisites)}")

    # Action items
    if article.action_items:
        parts.append(f"<h2>Action Items</h2>{_bullet_list(article.action_items)}")

    # Metadata table with status badge for severity
    meta_rows = f"<tr><th>Type</th><td>{article.incident_type}</td></tr>"
    if article.severity:
        meta_rows += f"<tr><th>Severity</th><td>{_status_badge(article.severity)}</td></tr>"
    if article.systems_affected:
        meta_rows += f"<tr><th>Systems Affected</th><td>{', '.join(article.systems_affected)}</td></tr>"
    meta_rows += f"<tr><th>Confidence Score</th><td>{int(article.confidence_score * 100)}%</td></tr>"
    parts.append(f"<h2>Metadata</h2><table><tbody>{meta_rows}</tbody></table>")

    # Footer — attribution panel
    parts.append(
        _macro(
            "info",
            "<p>This article was generated by <strong>Documentation Agent</strong> using Claude AI. "
            "AI-generated content — review for accuracy before publishing.</p>",
        )
    )

    return "".join(parts)


def create_page(article: KBArticle) -> tuple[str, str]:
    """
    Create a Confluence page for the KB article.
    Returns (page_url, page_id).
    """
    space_key = os.environ["CONFLUENCE_SPACE_KEY"]
    base = _base_url()
    headers = {
        "Authorization": _auth_header(),
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    body: dict = {
        "type": "page",
        "title": article.title,
        "space": {"key": space_key},
        "body": {
            "storage": {
                "value": _build_body(article),
                "representation": "storage",
            }
        },
        "metadata": {
            "properties": {
                "editor": {"key": "editor", "value": "v2"}
            }
        },
    }

    parent_page_id = os.environ.get("CONFLUENCE_PARENT_PAGE_ID")
    if parent_page_id:
        body["ancestors"] = [{"id": parent_page_id}]

    with httpx.Client() as client:
        response = client.post(
            f"{base}/rest/api/content",
            headers=headers,
            json=body,
            timeout=15,
        )
        if response.status_code not in (200, 201):
            raise RuntimeError(
                f"Confluence page creation failed: {response.status_code} {response.text}"
            )
        data = response.json()
        page_id = data["id"]
        page_url = f"{base}/spaces/{space_key}/pages/{page_id}"

        if article.tags:
            labels = [{"name": tag} for tag in article.tags]
            client.post(
                f"{base}/rest/api/content/{page_id}/label",
                headers=headers,
                json=labels,
                timeout=10,
            )

    return page_url, page_id


def delete_page(page_id: str) -> None:
    """Delete a Confluence page by ID."""
    base = _base_url()
    headers = {"Authorization": _auth_header()}
    with httpx.Client() as client:
        response = client.delete(
            f"{base}/rest/api/content/{page_id}",
            headers=headers,
            timeout=10,
        )
        if response.status_code not in (200, 204):
            raise RuntimeError(
                f"Failed to delete page {page_id}: {response.status_code} {response.text}"
            )


def list_space_pages() -> list[dict]:
    """List all pages in the demo space. Returns list of {id, title} dicts."""
    space_key = os.environ["CONFLUENCE_SPACE_KEY"]
    base = _base_url()
    headers = {"Authorization": _auth_header(), "Accept": "application/json"}
    pages = []
    start = 0
    with httpx.Client() as client:
        while True:
            response = client.get(
                f"{base}/rest/api/content",
                headers=headers,
                params={"spaceKey": space_key, "type": "page", "limit": 50, "start": start},
                timeout=10,
            )
            data = response.json()
            results = data.get("results", [])
            pages.extend({"id": p["id"], "title": p["title"]} for p in results)
            if len(results) < 50:
                break
            start += 50
    return pages
